#!/usr/bin/env ruby

require 'libroute'
require 'bson'

  options = Libroute.parse(ARGV)

  if options.library.empty?
    puts "Error: No LIBRARY specified"
    exit 1
  end

  if !options.build.empty?
    puts "Building #{options.library} library..."
    Libroute.build(options)
    exit 0
  end

  # Populate params
  paramshash = Hash.new
  if !options.params.empty?
    params = options.params.split(",")
    params.each do |p|
      key,val = p.split("=",2)
      paramshash[key]=val
    end
  end

  # Populate stdin
  if !$stdin.tty?
    data = $stdin.read
    if !data.nil?
      paramshash['stdin'] = BSON::Binary.new(data)
    end
  end

  result = Libroute.exec(options.library, paramshash)
  if !result['stdout'].nil?
    if result['stdout'].is_a?(String)
      puts result['stdout']
    else
      bb = result['stdout'].data
      puts bb.to_s
    end
  else
    result.each do |k,v|
      if v.length < 100
        puts k + ": " + v
      else
        puts k + ": #{v.length} bytes"
      end
    end
  end

