#!/usr/bin/env ruby

require 'libroute'


  options = Libroute.parse(ARGV)

  if options.library.empty?
    puts "Error: No LIBRARY specified"
    exit 1
  end

  if !options.build.empty?
    puts "Building #{options.library} library... (todo)"
    Libroute.build(options)
    exit 0
  end

  params = options.params.split(",")
  paramshash = Hash.new
  params.each do |p|
    key,val = p.split("=",2)
    paramshash[key]=val
  end

  result = Libroute.exec(options.library, paramshash)
  if !result['stdout'].nil?
    bb = result['stdout'].data
    puts bb.to_s
  else
    result.each do |k,v|
      if v.length < 100
        puts k + ": " + v
      else
        puts k + ": #{v.length} bytes"
      end
    end
  end

